# -*- coding: utf-8 -*-
"""Economics_ETA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fyf83coSO7x0Y-slAbnKii1nXS8GeAJR

https://www.youtube.com/watch?v=R67XuYc9NQ4

this is the video used to help with the coding aprt of this
"""

!pip install fredapi

"""https://fred.stlouisfed.org/docs/api/fred/ this is the website from where we are going to full our data"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
plt.style.use('fivethirtyeight')
#pd.set_option('max_columns',500)
color_pal = plt.rcParams['axes.prop_cycle'].by_key()['color'] #we can get different kind of numbers

from fredapi import Fred

import warnings
warnings.filterwarnings('ignore')

fred_key ='8f92790bfaa6ac360b65119400eb86bc'

"""# 1.Create the Fred Object"""

fred= Fred(api_key = fred_key)

"""# 2. Search For Economic Data!"""

sp_search = fred.search('S&P', order_by='popularity')

sp_search

"""# 3. Pull Raw Data"""

sp500=fred.get_series(series_id='SP500')

sp500.plot(figsize=(10,5),title= 'S&P 500',lw= 2)

"""# 4. Pull and Join Multiple Data Series"""

unemp_df = fred.search('unemployment rate state', filter=('frequency','Monthly'))
unemp_df = unemp_df.query('seasonal_adjustment == "Seasonally Adjusted" and units == "Percent"')
unemp_df = unemp_df.loc[unemp_df['title'].str.contains('Unemployment Rate')]

import time

all_results = []
# this is to pull the series from the ID
for myid in unemp_df.index:
    results = fred.get_series(myid)
    results = results.to_frame(name=myid)
    all_results.append(results)
    time.sleep(0.1) # Don't request to fast and get blocked
uemp_results = pd.concat(all_results, axis=1)

cols_to_drop = []
for i in uemp_results:
    if len(i) > 4:
        cols_to_drop.append(i)
uemp_results = uemp_results.drop(columns = cols_to_drop, axis=1)

uemp_states = uemp_results.copy()  #.drop('UNRATE', axis=1)
uemp_states = uemp_states.dropna()
id_to_state = unemp_df['title'].str.replace('Unemployment Rate in ','').to_dict() # creating a dictionary for full form of the states
uemp_states.columns = [id_to_state[c] for c in uemp_states.columns]  #this is the maping for our dictionary

uemp_states.isna().sum(axis=1).plot()  #to check if we have monthly status

px.line(uemp_states) #plot state unemployment rate

"""# 5. Pull Feb 2025 Umployment Rate Per State"""

ax = uemp_states.loc[uemp_states.index == '2025-02-01'].T \
    .sort_values('2025-02-01') \
    .plot(kind='barh', figsize=(8, 12), width=0.7, edgecolor='black',
          title='Unemployment Rate by State, May 2020')
ax.legend().remove()
ax.set_xlabel('% Unemployed')
plt.show()
# just by using barh we can get the we got a verticle graph

"""# Pull Participation Rate
Participation rate - indicator of people participating in the job market
"""

uemp_states = uemp_states.rename(columns={'the District of Columbia':'District Of Columbia'})

part_df = fred.search('participation rate state', filter=('frequency','Monthly'))
part_df = part_df.query('seasonal_adjustment == "Seasonally Adjusted" and units == "Percent"')

part_id_to_state = part_df['title'].str.replace('Labor Force Participation Rate for ','').to_dict()

all_results = []

for myid in part_df.index:
    results = fred.get_series(myid)
    results = results.to_frame(name=myid)
    all_results.append(results)
    time.sleep(0.1) # Don't request to fast and get blocked
part_states = pd.concat(all_results, axis=1)
part_states.columns = [part_id_to_state[c] for c in part_states.columns]

part_states

"""Plot Unemployment vs Participation"""

fig, axs = plt.subplots(10, 5, figsize=(30, 30), sharex=True)
axs = axs.flatten()

i = 0
for state in uemp_states.columns:
    if state in ["District Of Columbia","Puerto Rico"]:
        continue
    ax2 = axs[i].twinx()
    uemp_states.query('index >= 2022 and index < 2025')[state] \
        .plot(ax=axs[i], label='Unemployment')
    part_states.query('index >= 2022 and index < 2025')[state] \
        .plot(ax=ax2, label='Participation', color=color_pal[1])
    ax2.grid(False)
    axs[i].set_title(state)
    i += 1
plt.tight_layout()
plt.show()

state = 'California'
fig, ax = plt.subplots(figsize=(10, 5), sharex=True)
ax2 = ax.twinx()
uemp_states2 = uemp_states.asfreq('MS')
l1 = uemp_states2.query('index >= 2022 and index < 2025')[state] \
    .plot(ax=ax, label='Unemployment')
l2 = part_states.dropna().query('index >= 2022 and index < 2025')[state] \
    .plot(ax=ax2, label='Participation', color=color_pal[1])
ax2.grid(False)
ax.set_title(state)
fig.legend(labels=['Unemployment','Participation'])
plt.show()